name: flrx
description: "An opinionated application Framework using redux for the State Management."
version: 0.0.12
homepage: https://github.com/flrx/framework

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0
  catcher: ^0.6.8
  collection: ^1.15.0
  dio: ^4.0.6
  data_fixture_dart: ^2.1.0
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  get_it: ^7.2.0
  grammer: ^1.0.2
  logger: ^1.1.0
  logging: ^1.0.2
  meta: ^1.7.0
  path: ^1.8.0
  recase: ^4.0.0
  redux: ^5.0.0
  redux_logging: ^0.5.0
  redux_thunk: ^0.4.0
  stack_trace: ^1.10.0
  shared_preferences: ^2.0.13
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.4
  dart_code_metrics: ^4.5.0
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  test: ^1.17.10
