name: flrx
description: A Redux Application Framework.
version: 0.0.6
author: Flrx Team <flrx.dev@gmail.com>
homepage: https://github.com/flrx/framework

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  args: ^2.0.0
  flrx_validator: ^0.4.0+2
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_i18n: ^0.22.3
  flutter_redux: ^0.8.2
  get_it: ^6.0.0
  logging: ^1.0.1
  meta: ^1.2.4
  path: ^1.7.0
  recase: ^3.0.1
  redux: ^5.0.0
  redux_logging: ^0.5.0
  redux_thunk: ^0.4.0
  sentry: ^3.0.1
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
  pedantic: ^1.9.2
  test: ^1.15.6
