name: flrx
description: A Redux Application Framework.
version: 0.0.5
author: Flrx Team <flrx.dev@gmail.com>
homepage: https://github.com/flrx/framework

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Flutter Specific Packages
  flutter_i18n: ^0.20.1
  fluro: ^1.7.7
  flutter_redux: ^0.7.0
  sentry: ^3.0.1

  # Dart 2 Packages
  meta: ^1.2.4
  logging: ^0.11.4
  logger: ^0.9.4
  flrx_validator: ^0.4.0+2
  redux: ^4.0.0
  redux_logging: ^0.4.0
  redux_thunk: ^0.3.0
  get_it: ^5.0.1
  args: ^1.6.0
  path: ^1.7.0
  yaml: ^2.2.1
  recase: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  mockito: ^4.1.3
  test: ^1.15.6
