name: flrx
description: A Redux Application Framework.
version: 0.0.2+2
author: flrx
homepage: https://github.com/flrx/framework

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^2.0.22
  sentry: ^2.2.0
  flutter_i18n: ^0.6.3
  fluro: ^1.4.0
  flutter_redux: ^0.5.3
  redux_logging: ^0.3.0
  redux_thunk: ^0.2.1
  redux_persist_flutter: ^0.8.1
  get_it: ^1.0.3
  args: ^1.5.1
  path: ^1.6.2
  yaml: ^2.1.15
  recase: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
