name: flrx
description: A Redux Application Framework.
version: 0.0.6
author: Flrx Team <flrx.dev@gmail.com>
homepage: https://github.com/flrx/framework

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  catcher: ^0.6.7
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_i18n: ^0.22.3
  flutter_redux: ^0.8.2
  get_it: ^7.0.0
  logging: ^1.0.1
  meta: ^1.3.0
  path: ^1.8.0
  recase: ^4.0.0
  redux: ^5.0.0
  redux_logging: ^0.5.0
  redux_thunk: ^0.4.0
  sentry: ^5.0.0
  yaml: ^3.1.0


dev_dependencies:
  build_runner: ^2.0.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7
  pedantic: ^1.11.0
  test: ^1.16.5
