// Mocks generated by Mockito 5.0.3 from annotations
// in flrx/test/mocks.dart.
// Do not manually edit this file.

import 'package:flrx/components/logger/base_logger.dart' as i3;
import 'package:mockito/mockito.dart' as i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends i1.Mock implements i3.Logger {}
