name: flrx_test
description: "Testing helpers and utilities for flrx framework."

version: 0.0.3
homepage: https://github.com/flrx/framework

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  redux: ^5.0.0
  shared_preferences: ^2.2.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flrx: ^0.0.12

dev_dependencies:
  flutter_lints: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
