name: flrx_test
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/flrx/framework

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  redux: ^5.0.0
  shared_preferences: ^2.0.13
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flrx: ^0.0.9

dev_dependencies:
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
